name: Master CI

on:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
      
    - name: Install
      run: yarn
      
    - name: Build
      run: yarn build

    - name: Test
      run: yarn test --updateSnapshot
